### ISSUE TITLE
[FEATURE] Company List cache

### ISSUE THREAD

**Issue by YoshihitoAso** [BoostryJP/ibet-Wallet-API#1058]
**Is your feature request related to a problem? Please describe.**

- Currently, the company list is cached as a cache of token information.
- There is no cache mechanism for direct references to the company list.
- We would like to build a cache mechanism in case of a connection failure.

**Describe the solution you'd like**

- The following methods are under consideration.
  - Store the data of a successful connection in the DB.
  - During the cache validity period, the data in the DB is referenced.

**Comment by urushibata-k** [comment]
- Store in DB in synchronization with EPrime's company list by batch processing.
- API gets from DB and returns it.
