### ISSUE TITLE
[FEATURE] Upgrade to python 3.11

### ISSUE THREAD

**Issue by YoshihitoAso** [BoostryJP/ibet-Wallet-API#1231]
https://www.python.org/downloads/release/python-3110/

**Comment by YoshihitoAso** [comment]
There is a issue with Web3py version upgrade.
https://github.com/ethereum/web3.py/pull/2699

**Comment by purplesmoke05** [comment]
web3.py v6 migration summary
- `base58` / `ipfshttpclient` are required to test dependencies.
- `web3.eth.getLogs` is renamed to `.get_logs`.(and all arguments are replaced to snake_case).
- `isAddress` is renamed to `is_address`.
- `web3.eth.account.privateKey` is renamed to `.key`

sample: https://github.com/BoostryJP/ibet-Wallet-API/tree/feature/web3-v6-upgrade
