### ISSUE TITLE
[FEATURE] Upgrade sqlalchemy-migrate to migrate db on sqlalchemy2 environment

### ISSUE THREAD

**Issue by purplesmoke05** [BoostryJP/ibet-Wallet-API#1338]
## Is your feature request related to a problem? Please describe.

- SQLAlchemy-migrate is not maintained 
- So it should be 
  - replaced with Alembic.
  - patched.

## Describe the solution you'd like

- Replace sqlalchemy-migrate with Alembic
- Update sqlalchemy-migrate to migrate db on sqlalchemy2 environment

**Comment by YoshihitoAso** [comment]
Our testing showed that sqlalchemy-migrate needed a lot of modifications to make it compatible with SQLAlchemy2. Also considering future maintenance stability, I think moving to Alembic is the best choice.
